### ISSUE TITLE
version info of dependent libs

### ISSUE THREAD

**Issue by chcg** [azerg/NppPlistPlugin#3]
For contribution to further development it might be helpfull to know the versions of the externals:

- https://github.com/libimobiledevice/libplist/releases
- http://xmlsoft.org/news.html

used currently as basis and if it is modified.

**Comment by azerg** [comment]
Yea, i will add this info with a new release of plugin. Hard to know what version we are using now :(

**Comment by azerg** [comment]
I'll add task to my short-list, to finish soon, but could not fit this in latest release.

**Comment by azerg** [comment]
In a new [https://github.com/azerg/NppBplistPlugin/releases/tag/2.0.0](2.0.0 release), added exact versioning of dependencies/ Going to register plugin update ASAP
