### ISSUE TITLE
Version info in 1.2.0.3 is 1.2.0.0

### ISSUE THREAD

**Issue by sunjw** [azerg/NppPlistPlugin#5]
Download https://github.com/azerg/NppBplistPlugin/releases/download/1.2.0.3/NppBplistPlugin_x86.zip
Unzip to C:\Downloads\NppBplistPlugin.dll, found:
Size: 2054656 Byte (1.96 MB)
Modified: 2017-01-27 21:34
Version: **1.2.0.0**
MD5: db2d3ea89a526b9f315d3b0053770a93
SHA1: 6427201900041159d11d488e976b9a85dbda5be9
SHA256: 0c7f53d480d199c0cda37596747873d3e7e6365f3225abfa23e7a47edf0d3a44
CRC32: 77e20d7a

**Comment by sunjw** [comment]
Also in x64 build, version info says 1.2.0.0.

**Comment by azerg** [comment]
Thanks. Will recompile with updated version info soon 🏎

**Comment by azerg** [comment]
fixed in 1.2.0.4
